name: Pylint

on: [push]

jobs:
  build:
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=invalid-name --disable=duplicate-code --ignore="Login.py, coursebatch.py, populate.py, populateold.py, userbatch.py, createtable-courses.py, createtable-users.py, createtable-subjects.py, starterPopulation.py, GetSubjectTable.py, GetSubjectTableAdmin.py, GetEnrolledList.py, GetCourseSections.py, GetCourseInformation.py, AddCourse.py, DropCourse.py, GetCourseInfoTeacher.py, GetEnrolledListTeacher.py" $(git ls-files '*.py')
